version: '3'

services:
  app:
    build: .
    container_name: "Flask_App"
    links:
      - db
    ports:
      - "5000:5000"
  
  
  db:
    image: mysql:latest
    ports:
      - "32000:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      
    volumes:
      - ./data/mysql:/var/lib/mysql

